# Generated by Django 5.1.4 on 2026-05-15 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAPIWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('request_body', models.TextField(blank=True)),
                ('response_status', models.IntegerField(null=True)),
                ('response_body', models.TextField(blank=True)),
                ('duracion_ms', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Log API WhatsApp',
                'verbose_name_plural': 'Logs API WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaHSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_meta', models.CharField(blank=True, help_text='Nombre exacto en Meta Business Manager', max_length=100)),
                ('categoria', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utilidad'), ('AUTHENTICATION', 'Autenticación')], default='MARKETING', max_length=30)),
                ('idioma', models.CharField(default='es_AR', max_length=10)),
                ('cuerpo', models.TextField(help_text='Texto de la plantilla. Usar {{1}}, {{2}}... para variables.')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Lista de nombres de variables, en orden.')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla HSM',
                'verbose_name_plural': 'Plantillas HSM',
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=200)),
                ('ultimo_mensaje_at', models.DateTimeField(blank=True, null=True)),
                ('mensajes_no_leidos', models.PositiveIntegerField(default=0)),
                ('ventana_activa', models.BooleanField(default=False)),
                ('ventana_expira_at', models.DateTimeField(blank=True, null=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversacion_whatsapp', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-ultimo_mensaje_at'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_message_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('direccion', models.CharField(choices=[('in', 'Entrante'), ('out', 'Saliente')], max_length=3)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('document', 'Documento'), ('audio', 'Audio'), ('template', 'Plantilla HSM')], default='text', max_length=20)),
                ('contenido', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('media_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('error_detalle', models.TextField(blank=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='whatsapp.conversacion')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_whatsapp', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['timestamp'],
            },
        ),
    ]
