# Generated by Django 5.1.4 on 2026-05-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_bot_respuesta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantillahsm',
            options={'ordering': ['nombre'], 'verbose_name': 'Plantilla HSM', 'verbose_name_plural': 'Plantillas HSM'},
        ),
        migrations.AlterField(
            model_name='botrespuesta',
            name='accion_estado',
            field=models.CharField(blank=True, help_text='Dejar vacío para no cambiar el estado', max_length=20, verbose_name='Cambiar estado del lead a'),
        ),
        migrations.AlterField(
            model_name='botrespuesta',
            name='accion_prioridad',
            field=models.CharField(blank=True, help_text='Dejar vacío para no cambiar la prioridad', max_length=10, verbose_name='Cambiar prioridad del lead a'),
        ),
        migrations.AlterField(
            model_name='botrespuesta',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0, help_text='Menor número = mayor prioridad'),
        ),
        migrations.AlterField(
            model_name='botrespuesta',
            name='palabras_clave',
            field=models.JSONField(blank=True, default=list, help_text='Lista de palabras/frases. Coincidencia parcial, sin distinción de mayúsculas. Ej: ["precio", "info", "quiero"]', verbose_name='Palabras clave'),
        ),
        migrations.AlterField(
            model_name='botrespuesta',
            name='respuesta_interactivo_botones',
            field=models.JSONField(blank=True, default=list, help_text='[{"id":"btn_1","title":"Sí, quiero información"}]', verbose_name='Botones'),
        ),
        migrations.AlterField(
            model_name='plantillahsm',
            name='botones',
            field=models.JSONField(blank=True, default=list, help_text='[{"tipo":"reply","texto":"Sí, me interesa"},{"tipo":"url","texto":"Ver planes","valor":"https://..."}]', verbose_name='Botones'),
        ),
        migrations.AlterField(
            model_name='plantillahsm',
            name='cuerpo',
            field=models.TextField(help_text='Texto principal. Usar {{1}}, {{2}}... para variables.'),
        ),
        migrations.AlterField(
            model_name='plantillahsm',
            name='header_contenido',
            field=models.TextField(blank=True, help_text='Texto del header (si tipo=Texto) o URL del archivo (imagen/video/documento)', verbose_name='Contenido del header'),
        ),
        migrations.AlterField(
            model_name='plantillahsm',
            name='nombre_meta',
            field=models.CharField(blank=True, help_text='Nombre en Meta (snake_case, sin espacios). Se genera automáticamente al enviar.', max_length=100),
        ),
        migrations.AlterField(
            model_name='plantillahsm',
            name='variables',
            field=models.JSONField(blank=True, default=list, help_text='Lista de nombres de variables en orden: ["nombre", "plan", ...]'),
        ),
    ]
