# Generated by Django 5.1.4 on 2026-05-15 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('interesado', 'Interesado'), ('doc_pendiente', 'Documentación pendiente'), ('en_revision', 'En revisión'), ('afiliado', 'Afiliado'), ('perdido', 'Perdido / No interesado')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('interesado', 'Interesado'), ('doc_pendiente', 'Documentación pendiente'), ('en_revision', 'En revisión'), ('afiliado', 'Afiliado'), ('perdido', 'Perdido / No interesado')], max_length=20)),
                ('nota', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('dni', models.CharField(db_index=True, max_length=8, validators=[django.core.validators.RegexValidator(message='El DNI debe tener entre 7 y 8 dígitos numéricos.', regex='^\\d{7,8}$')], verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe comenzar con +54 seguido de 10-12 dígitos.', regex='^\\+54\\d{10,12}$')], verbose_name='Teléfono (WhatsApp)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('localidad', models.CharField(blank=True, max_length=100, verbose_name='Localidad')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('grupo_familiar', models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad grupo familiar')),
                ('origen', models.CharField(choices=[('web', 'Web'), ('campana', 'Campaña'), ('referido', 'Referido'), ('llamada', 'Llamada entrante'), ('whatsapp', 'WhatsApp')], default='web', max_length=20, verbose_name='Origen')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('interesado', 'Interesado'), ('doc_pendiente', 'Documentación pendiente'), ('en_revision', 'En revisión'), ('afiliado', 'Afiliado'), ('perdido', 'Perdido / No interesado')], db_index=True, default='nuevo', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['nombre'],
            },
        ),
    ]
