# Generated by Django 5.1.4 on 2026-05-21 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
        ('leads', '0003_lead_datos_extra'),
        ('whatsapp', '0004_alter_plantillahsm_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='automatizacionlog',
            name='unique_regla_lead',
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='accion_estado_destino',
            field=models.CharField(blank=True, help_text='Para acción "cambiar estado"', max_length=20, verbose_name='Estado destino'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='accion_plantilla',
            field=models.ForeignKey(blank=True, help_text='Para acción "enviar plantilla WhatsApp"', null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.plantillahsm', verbose_name='Plantilla HSM'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='accion_prioridad_destino',
            field=models.CharField(blank=True, help_text='Para acción "cambiar prioridad"', max_length=10, verbose_name='Prioridad destino'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='accion_tarea_descripcion',
            field=models.TextField(blank=True, help_text='Para acción "crear tarea". Podés usar {lead} para el nombre del lead.', verbose_name='Descripción de la tarea'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='accion_tarea_dias_plazo',
            field=models.PositiveSmallIntegerField(default=1, help_text='Días desde hoy para la fecha programada de la tarea', verbose_name='Plazo de la tarea (días)'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='condicion_estado',
            field=models.CharField(blank=True, help_text='Dejar vacío para cualquier estado', max_length=20, verbose_name='Solo si estado es'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='condicion_origen',
            field=models.CharField(blank=True, help_text='Dejar vacío para cualquier origen', max_length=20, verbose_name='Solo si origen es'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='condicion_prioridad',
            field=models.CharField(blank=True, help_text='Dejar vacío para cualquier prioridad', max_length=10, verbose_name='Solo si prioridad es'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='trigger_dias',
            field=models.PositiveSmallIntegerField(help_text='Número de días para el disparador', verbose_name='Días'),
        ),
        migrations.AlterUniqueTogether(
            name='automatizacionlog',
            unique_together={('regla', 'lead')},
        ),
    ]
