# Generated by Django 5.1.4 on 2026-05-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_integrantes', models.PositiveSmallIntegerField(default=1)),
                ('monto_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='borrador', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='cotizaciones/pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegranteFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=8)),
                ('fecha_nacimiento', models.DateField()),
                ('parentesco', models.CharField(choices=[('titular', 'Titular'), ('conyuge', 'Cónyuge'), ('hijo', 'Hijo/a'), ('otro', 'Otro')], default='titular', max_length=20)),
            ],
            options={
                'verbose_name': 'Integrante familiar',
                'verbose_name_plural': 'Integrantes familiares',
            },
        ),
    ]
