# Generated by Django 5.1.4 on 2026-05-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada'), ('whatsapp', 'WhatsApp'), ('reunion', 'Reunión'), ('documentacion', 'Envío de documentación'), ('seguimiento', 'Seguimiento')], default='seguimiento', max_length=20)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_programada', models.DateTimeField(verbose_name='Fecha y hora programada')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('vencida', 'Vencida')], db_index=True, default='pendiente', max_length=20)),
                ('resultado', models.TextField(blank=True, verbose_name='Resultado / nota de completado')),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['fecha_programada'],
            },
        ),
    ]
