# Generated by Django 5.1.4 on 2026-05-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('filtros_segmento', models.JSONField(blank=True, default=dict, help_text='Filtros de segmento: estado, plan_id, provincia, dias_sin_contacto')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('programada', 'Programada'), ('en_ejecucion', 'En ejecución'), ('completada', 'Completada')], default='borrador', max_length=20)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('total_destinatarios', models.PositiveIntegerField(default=0)),
                ('enviados', models.PositiveIntegerField(default=0)),
                ('entregados', models.PositiveIntegerField(default=0)),
                ('leidos', models.PositiveIntegerField(default=0)),
                ('errores', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampanaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('error', 'Error')], max_length=10)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100)),
                ('error_detalle', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de campaña',
                'verbose_name_plural': 'Logs de campaña',
            },
        ),
    ]
